# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\commission.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from config_done import *
from prompts import Prompt

class Ui_CommissioningWindow(object):
    def setupUi(self, CommissioningWindow):
        CommissioningWindow.setObjectName("CommissioningWindow")
        CommissioningWindow.resize(384, 132)
        self.verticalLayoutWidget = QtWidgets.QWidget(CommissioningWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(29, 39, 341, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton.clicked.connect(self.AddingSystem)

        self.retranslateUi(CommissioningWindow)
        QtCore.QMetaObject.connectSlotsByName(CommissioningWindow)

    def retranslateUi(self, CommissioningWindow):
        _translate = QtCore.QCoreApplication.translate
        CommissioningWindow.setWindowTitle(_translate("CommissioningWindow", "Commissioning"))
        self.label.setText(_translate("CommissioningWindow", "Enter Serial Number:"))
        self.pushButton.setText(_translate("CommissioningWindow", "Commission"))


    def AddingSystem(self):
        system_serial_number = self.lineEdit.text().upper()
        comm = configparser.ConfigParser()
        comm.read(f"{gui_global.files_directory_location}profile.txt")
        Section = comm['COMMISSION']

        for option in Section:
            Section[option] = system_serial_number

        with open(f'{gui_global.files_directory_location}profile.txt', 'w') as conFile:
            comm.write(conFile)
        conFile.close()

        Prompt.Message(Prompt, "Done!", "System serial number accepted ;)")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CommissioningWindow = QtWidgets.QWidget()
    ui = Ui_CommissioningWindow()
    ui.setupUi(CommissioningWindow)
    CommissioningWindow.show()
    sys.exit(app.exec_())
