# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Custom.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

from config_done import *

# 15234

apply_bit = 1
count = 0

class Ui_custom(QDialog):
    def __init__(self):
        super().__init__()


    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(394, 376)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f"{gui_global.image_directory_location}logo_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        widget.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(widget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 371, 211))
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setMaximum(999)
        self.horizontalLayout.addWidget(self.spinBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 351, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_2.setMaximum(999)
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 130, 351, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_3.addWidget(self.checkBox_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.spinBox_3 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_3.setMaximum(999)
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 170, 351, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_4.addWidget(self.checkBox_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.spinBox_4 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_4.setMaximum(999)
        self.horizontalLayout_4.addWidget(self.spinBox_4)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 50, 351, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_5.addWidget(self.checkBox_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.spinBox_5 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_5)
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_5.setMaximum(999)
        self.horizontalLayout_5.addWidget(self.spinBox_5)
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 371, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 2px solid green")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(widget)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 371, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 2px solid red")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(widget)
        self.pushButton.setGeometry(QtCore.QRect(160, 330, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setMouseTracking(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.WriteValues)
        # self.pushButton_2 = QtWidgets.QPushButton(widget)
        # self.pushButton_2.setGeometry(QtCore.QRect(230, 330, 81, 31))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_2.setFont(font)
        # self.pushButton_2.setObjectName("pushButton_2")
        # self.pushButton_3 = QtWidgets.QPushButton(widget)
        # self.pushButton_3.setGeometry(QtCore.QRect(260, 330, 81, 31))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_3.setFont(font)
        # self.pushButton_3.setObjectName("pushButton_3")
        # self.pushButton_3.clicked.connect(self.close)
        self.groupBox_2 = QtWidgets.QGroupBox(widget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 371, 31))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 371, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)
        self.ReadValues()

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Custom Setting"))
        self.checkBox.setText(_translate("widget", "SET SMR COUNT"))
        self.checkBox_2.setText(_translate("widget", "SYSTEM OVERLOAD CAPACITY"))
        self.checkBox_3.setText(_translate("widget", "BATTERY (AH)"))
        self.checkBox_4.setText(_translate("widget", "COMM SMR COUNT"))
        self.checkBox_5.setText(_translate("widget", "MAX SMR COUNT"))
        self.label_2.setText(_translate("widget", "NOTE: Leave check blank in case of no value"))
        self.label_3.setText(_translate("widget", "WARNING: These values will over ride config file values"))
        self.pushButton.setText(_translate("widget", "Apply"))
        # self.pushButton_2.setText(_translate("widget", "Fetch"))
        # self.pushButton_3.setText(_translate("widget", "Cancel"))
        self.label.setText(_translate("widget", "Custom Default Values"))

    def ReadValues(self):
        smr_count = int(DefaultRead('DEFAULT SETTING')['smr count'])
        system_overload = int(DefaultRead("DEFAULT SETTING")['system overload'])
        battery_ah = int(DefaultRead("DEFAULT SETTING")['battery ah'])
        max_smr_count = int(DefaultRead("DEFAULT SETTING")['max smr count'])
        comm_smr_count = int(DefaultRead("DEFAULT SETTING")['comm smr count'])

        self.spinBox.setValue(smr_count)
        self.spinBox_5.setValue(max_smr_count)
        self.spinBox_2.setValue(system_overload)
        self.spinBox_3.setValue(battery_ah)
        self.spinBox_4.setValue(comm_smr_count)

        smr_flag = str(DefaultRead('DEFAULT SETTING STATE')['smr count'])
        system_flag = str(DefaultRead("DEFAULT SETTING STATE")['system overload'])
        battery_flag = str(DefaultRead("DEFAULT SETTING STATE")['battery ah'])
        max_smr_flag = str(DefaultRead("DEFAULT SETTING STATE")['max smr count'])
        comm_smr_flag = str(DefaultRead("DEFAULT SETTING STATE")['comm smr count'])

        if smr_flag == "YES":
            self.checkBox.setChecked(True)
        else:
            self.checkBox.setChecked(False)

        if system_flag == "YES":
            self.checkBox_2.setChecked(True)
        else:
            self.checkBox_2.setChecked(False)

        if battery_flag == "YES":
            self.checkBox_3.setChecked(True)
        else:
            self.checkBox_3.setChecked(False)

        if comm_smr_flag == "YES":
            self.checkBox_4.setChecked(True)
        else:
            self.checkBox_4.setChecked(False)

        if max_smr_flag == "YES":
            self.checkBox_5.setChecked(True)
        else:
            self.checkBox_5.setChecked(False)

        self.OFFState(True)

        self.pushButton.setText("Change")



    def WriteValues(self):
        global count

        if self.pushButton.pressed:
            count += 1

        if self.pushButton.text() == "Change" and count == 1:
            self.pushButton.setText("Apply")

            self.OFFState(False)

        if self.pushButton.text() == "Apply" and count == 2:
            self.OFFState(True)
            self.pushButton.setText("Change")

            smr_count = int(self.spinBox.value())
            system_overload = int(self.spinBox_2.value())
            battery_ah = int(self.spinBox_3.value())
            max_smr_count = int(self.spinBox_5.value())
            comm_smr_count = int(self.spinBox_4.value())
            # var_list = [smr_count, system_overload, battery_ah, max_smr_count, comm_smr_count]

            config.read(f"{gui_global.files_directory_location}default.txt")

            config['DEFAULT SETTING']['smr count'] = str(smr_count)
            config['DEFAULT SETTING']['system overload'] = str(system_overload)
            config['DEFAULT SETTING']['battery ah'] = str(battery_ah)
            config['DEFAULT SETTING']['max smr count'] = str(max_smr_count)
            config['DEFAULT SETTING']['comm smr count'] = str(comm_smr_count)

            if self.checkBox.isChecked():
                config['DEFAULT SETTING STATE']['smr count'] = "YES"
            else:
                config['DEFAULT SETTING STATE']['smr count'] = "NO"

            if self.checkBox_2.isChecked():
                config['DEFAULT SETTING STATE']['system overload'] = "YES"
            else:
                config['DEFAULT SETTING STATE']['system overload'] = "NO"

            if self.checkBox_3.isChecked():
                config['DEFAULT SETTING STATE']['battery ah'] = "YES"
            else:
                config['DEFAULT SETTING STATE']['battery ah'] = "NO"

            if self.checkBox_4.isChecked():
                config['DEFAULT SETTING STATE']['comm smr count'] = "YES"
            else:
                config['DEFAULT SETTING STATE']['comm smr count'] = "NO"

            if self.checkBox_5.isChecked():
                config['DEFAULT SETTING STATE']['max smr count'] = "YES"
            else:
                config['DEFAULT SETTING STATE']['max smr count'] = "NO"

            with open(f"{gui_global.files_directory_location}default.txt", 'w') as configfile:
                config.write(configfile)
            configfile.close()

        if count == 2:
            count = 0


    def OFFState(self, State: bool):
        self.spinBox.setDisabled(State)
        self.spinBox_2.setDisabled(State)
        self.spinBox_3.setDisabled(State)
        self.spinBox_4.setDisabled(State)
        self.spinBox_5.setDisabled(State)

        self.checkBox.setDisabled(State)
        self.checkBox_2.setDisabled(State)
        self.checkBox_3.setDisabled(State)
        self.checkBox_4.setDisabled(State)
        self.checkBox_5.setDisabled(State)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QDialog()
    ui = Ui_custom()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
